name: airpollution-planner
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.8
  - geopandas=0.9.0
  - rasterio=1.2.0
  - osmnx=1.9.2
  - networkx=3.3
  - pandas=2.2.2
  - geopy=2.4.1
  - pyqt=5.15.9
  - folium=0.16.0